### PR TITLE
 Fix #613: Notification bell does not light up for new users until the first time they click it

### LINKED ISSUE #613: Notification bell does not light up for new users until after the first time they click it?
EDIT: Originally, I had said that it did not work for me, user 'gwillen', but then they started working. My new theory is that it does not work for new users, and the user 'gwillen-test' is currently in this state if anybody needs an example to investigate. (The 'gwillen-test' account has no private information associated with it, and you may abuse it freely in any way you desire in order to try to debug this.)

@Raemon asked me to file this, after we figured out that the reason I thought notifications weren't a thing yet is that the bell icon never lights up for me, or otherwise indicates that I have any.

I am logged-in, on Chrome 67.0.3396.62, on OS X 10.12.6. I am running uBlock Origin 1.16.8 (adblock), and a few other extensions that really shouldn't be fucking it up but you know how these things are.

A couple of not-relevant-looking errors on console:

"""
p.typekit.net/p.gif?s=1&k=jvr1gjm&ht=tk&h=www.lesswrong.com&f=8498.8499.8500.8501.8502.8503.14739.14740.10954.13453.13454.13455.13456.13457.13458.13459.13460.13461&a=10927367&js=1.19.2&app=typekit&e=js&_=1527972246030:1 GET https://p.typekit.net/p.gif?s=1&k=jvr1gjm&ht=tk&h=www.lesswrong.com&f=8498.8499.8500.8501.8502.8503.14739.14740.10954.13453.13454.13455.13456.13457.13458.13459.13460.13461&a=10927367&js=1.19.2&app=typekit&e=js&_=1527972246030 0 ()
"""

"""
Mixed Content: The page at 'https://www.lesswrong.com/' was loaded over HTTPS, but requested an insecure favicon 'http://res.cloudinary.com/lesswrong-2-0/image/upload/v1497915096/favicon_lncumn.ico'. This request has been blocked; the content must be served over HTTPS.
"""

(Indeed, the favicon is not loading.)

### PR DESCRIPTION
**Pull request by jimrandomh**
https://github.com/LessWrong2/Lesswrong2/issues/613

### CODE REVIEW

File: packages/lesswrong/components/notifications/NotificationsMenu.jsx [hunk 1]
```diff
@@ -4,11 +4,11 @@ import PropTypes from 'prop-types';
...
-import AllIcon from '@material-ui/icons/Notifications';
-import ClearIcon from '@material-ui/icons/Clear';
-import PostsIcon from '@material-ui/icons/Description';
-import CommentsIcon from '@material-ui/icons/ModeComment';
-import MessagesIcon from '@material-ui/icons/Forum';
+import AllIcon from 'material-ui/svg-icons/social/notifications';
+import ClearIcon from 'material-ui/svg-icons/content/clear';
+import PostsIcon from 'material-ui/svg-icons/action/description';
+import CommentsIcon from 'material-ui/svg-icons/editor/mode-comment';
+import MessagesIcon from 'material-ui/svg-icons/communication/forum';
```
Comment (Discordius) [inline packages/lesswrong/components/notifications/NotificationsMenu.jsx]: Why did you revert the icons to the old material-ui format here? Did anything break?

File: packages/lesswrong/components/notifications/NotificationsList.jsx [hunk 2]
```diff
@@ -9,7 +9,7 @@ class NotificationsList extends Component {
   constructor(props) {
     super(props)
     this.state = {
-      lastNotificationsCheck: props.currentUser.lastNotificationsCheck,
+      lastNotificationsCheck: (props.currentUser.lastNotificationsCheck || ""),
```
Comment (Discordius) [inline packages/lesswrong/components/notifications/NotificationsList.jsx]: If we have this line, we should add currentUser as a required prop in proptypes, otherwise the check should be `props.currentUser && props.currentUser.lastNotificationsCheck || ""`

File: packages/lesswrong/components/notifications/NotificationsMenu.jsx (hunk 1 above)
Comment (jimrandomh) [reply packages/lesswrong/components/notifications/NotificationsMenu.jsx]: Ugh. I didn't - this is some sort of merge artifact. I'll investigate further when I get the chance tonight; best guess is I did a git operation with the file open in editor with unsaved changes. Usually I look at diffs as I'm adding things to a commit, but I must not have this time.
