### PR TITLE
Slow comment rendering; and, fix broken inbound legacy post links that omit the slug

### LINKED ISSUE #731: Links without any slugs from legacy lesswrong are still broken
From Jeff Kauffman: 

Hi Oliver,

I have a bunch of links to old lesswrong posts like:

    https://www.lesswrong.com/lw/lfn

It looks like all of these links broke with the transition.  If I
instead change them to:

    https://www.lesswrong.com/lw/lfn/anything-can-go-here/

then I get a redirect like:

    https://www.lesswrong.com/posts/B5auLtDfQrvwEkw4Q/we-haven-t-uploaded-worms

and it works.

I can fix these on my end if need be, but I wanted to check with you
to see if you wanted to fix them on yours?

### PR DESCRIPTION
**Pull request by jimrandomh**
Fixes #731 .

### CODE REVIEW

**Comment by jimrandomh** [comment]
Tested by giving a post on my local install a legacy ID, and visiting some legacy URLs for it with and without the slug. (The slug is the portion of the URL that gives the post name, to make the link more readable, which is ignored because the post ID is required.)

**Comment by jimrandomh** [comment]
Whoops, I meant to push that as a separate PR. I don't know how to undo that, so I'll rename this PR instead as being for both things..

File: packages/lesswrong/server/scripts/debuggingScripts.js [hunk 1]
```diff
@@ -56,3 +56,147 @@ Vulcan.populateNotifications = async ({username,
...
+}
+
+// Create a given number of paragraphs of a given length (in characters)
+// of lorem ipsum, formatted like:
+//   <p>Lorem ipsum dolor sit ame</p>
+// This is strictly for making big/slow posts for test purposes.
+function makeLoremIpsumBody(numParagraphs, paragraphLength) {
+  let result = [];
+  
+  for(var ii=0; ii<numParagraphs; ii++) {
```
Comment (Discordius) [inline packages/lesswrong/server/scripts/debuggingScripts.js]: Why????

Comment (jimrandomh) [reply packages/lesswrong/server/scripts/debuggingScripts.js]: Actual reason: I read a blog post arguing for `ii` rather than `i` a long time ago, adopted it, and forgot why.

I tracked down what that blog post would have said, and the only argument I see people making is that `ii` is easier to search for. But that doesn't apply when your search mechanism handles token boundaries correctly, so I don't have any reason other than habit now.

**Comment by jimrandomh** [comment]
Mostly resolves #708

**Comment by Discordius** [comment]
Ready to merge?
