### PR TITLE
LaTeX fixes

### LINKED ISSUE #1166: LaTeX vertical alignment
Inline LaTeX elements are vertically misaligned, typically too high. This is a regression that was introduced when I modified LaTeX to better handle wide elements. I gave them `overflow-x: auto`; this creates a horizontal scrollbar iff they exceed their maximum width. As discussed [here](https://stackoverflow.com/questions/43996242/whats-the-deal-with-vertical-align-baseline) and [here](https://stackoverflow.com/questions/4310047/css-why-is-vertical-align-baseline-stop-working-on-firefox-when-using-overflow):

> The inline-block element’s baseline depends on whether the element has in-flow content. In case of:
>
> * in-flow content the baseline of the inline-block element is the baseline of the last content element in normal flow (example on the left)
> * in-flow content but an overflow property evaluating to something other than visible, the baseline is the bottom edge of the margin-box (example in the middle)

Essentially, the problem is that `overflow: auto` only creates a scrollbar if it's actually needed, but it removes the baseline *regardless of whether it created a scrollbar*.

So, there are a number of options, but none of them is perfect.

Option 1: If we change the vertical-align from `baseline` to `middle`, this is an improvement, in that things are misaligned by a much smaller amount. But they're still misaligned. We could use client-side Javascript to inspect the rendered LaTeX and add scrollbars to actually-wide LaTeX elements, but this would be a painful hack.

Option 2: There are two kinds of LaTeX elements: inline LaTeX and block LaTeX. Only inline LaTeX needs vertical alignment. In principle, only block LaTeX gets large enough to need a scrollbar, *except* it turns out to be really easy to make a paragraph which consists only of an "inline" LaTeX element. So we could make a CSS rule that gives a LaTeX element `overflow-x: auto` if it either is a block element, or is inline but is the only child of its block. This handles most cases, but not the case where a long LaTeX expression is combined in a block with a little bit of other text, such as a list bullet.

Option 3: We take `overflow-x` off of the LaTeX elements, and move it up the tree to the paragraph elements. This introduces significant complexity due to the variety of possible paragraph-like element types, combined with the need for each to have an appropriate `max-width`; for example, a `blockquote` has some extra padding and/or margin, which means `max-width:100%` is probably too wide for it.

Overall I think I lean towards option 2.

### LINKED ISSUE #1168: LaTeX editor height and style
The LaTeX editor in draft-js gets `<textarea>` styles applied to it, which it shouldn't.

### PR DESCRIPTION
**Pull request by jimrandomh**
Fixes the height of the LaTeX editor in DraftJS. Fixes vertical alignment of inline LaTeX elements, at the cost of them being able to overflow and make the whole page scroll.

Fixes #1168. Fixes #1166.

### CODE REVIEW

File: packages/lesswrong/components/editor/EditorFormComponent.jsx [hunk 1]
```diff
@@ -7,36 +7,43 @@ import { editorStyles, postBodyStyles, commentBodyStyles } from '../../themes/st
 import Typography from '@material-ui/core/Typography';
 import withUser from '../common/withUser';
 import DraftJSEditor from '../async/EditorFormContainer'
+import classnames from 'classnames';
 
-const postEditorHeight = 250;
-const commentEditorHeight = 100;
+const postEditorHeightPx = 250;
```
Comment (Raemon) [inline packages/lesswrong/components/editor/EditorFormComponent.jsx]: revert this to not have the name change I guess?
