### PR TITLE
Fix ToC LaTeX

### LINKED ISSUE #2962: LaTeX in headers breaks ToC
Screen Shot 2020-03-08 at 5 36 19 PM

### PR DESCRIPTION
**Pull request by jimrandomh**
Fixes #2962 . Currently when a (DraftJS) post has LaTeX in a section heading, the stylesheet ends up embedded in the section title, which looks ridiculous and effectively breaks the ToC; this filters <style> nodes out. Also improves the error handling of the ToC so that a crash in ToC extraction won't break the page (not that that has ever happened).

### CODE REVIEW

File: packages/lesswrong/lib/collections/posts/custom_fields.ts [hunk 1]
```diff
@@ -914,7 +915,12 @@ addFieldsDict(Posts, {
     viewableBy: ['guests'],
     graphQLtype: GraphQLJSON,
     resolver: async (document, args, { currentUser }) => {
-      return await Utils.getTableOfContentsData({document, version: null, currentUser});
+      try {
+        return await Utils.getTableOfContentsData({document, version: null, currentUser});
+      } catch(e) {
+        Sentry.captureException(e);
```
Comment (Raemon) [inline packages/lesswrong/lib/collections/posts/custom_fields.ts:921]: Is this how we're basically supposed to handle all errors? (I don't know that I've actually done any explicit error handling, but didn't have this as part of my workflow)

Comment (jimrandomh) [reply packages/lesswrong/lib/collections/posts/custom_fields.ts:921]: Sometimes. Sort-of. If you do put a try-catch block around something, this is what it should look like, but try-catch blocks should be used sparingly. The client-side equivalent of this sort of thing is `withErrorBoundary`.

If you do put a try-catch around something and expect that it might suppress an error, then `Sentry.captureException` is the way to make sure we eventually notice and investigate that error. (If we didn't have something like `Sentry.captureException`, this would be a software anti-pattern called exception swallowing, which is very bad.)

Try-catch blocks like this can make things better in cases where (1) they cover a lot of code, or risky code, and (2) crashes in that code would otherwise break more than the code is responsible for. The purpose is to limit the scope of the breakage, if there's a bug. In this case, without the try-catch block, a bug in ToC generation would break the whole post page, whereas with the try-catch block, you get a working post page without a table of contents, which is better.

(I noticed this while working on the ToC code, when I made a version that crashed. We haven't had any problems with it crashing in production, so this is speculative.)

**Comment by Raemon** [comment]
This causes non-LaTeX headings to disappear. https://github.com/LessWrong2/Lesswrong2/issues/3187
