### PR TITLE
Fix EditorFormComponent emptying when changing editor type

### LINKED ISSUE #1835: Editor breaks when switching editor type

### PR DESCRIPTION
**Pull request by jimrandomh**
Fixes #1835. The bug was introduced in https://github.com/LessWrong2/Lesswrong2/pull/1709 .

### CODE REVIEW

File: packages/lesswrong/components/editor/EditorFormComponent.jsx [hunk 1]
```diff
@@ -309,7 +309,7 @@ class EditorFormComponent extends Component {
     const { type } = (value && value.originalContents) || (document[fieldName] && document[fieldName].originalContents) || {}
     return <Typography variant="body2" color="primary">
       This document was last edited in {type} format. Showing {this.getCurrentEditorType()} editor.
-      <a className={classes.errorTextColor} onClick={this.handleEditorOverride}> Click here </a>
+      <a className={classes.errorTextColor} onClick={() => this.handleEditorOverride(null)}> Click here </a>
```
Comment (Discordius) [inline packages/lesswrong/components/editor/EditorFormComponent.jsx]:
```suggestion
      <a className={classes.errorTextColor} onClick={() => this.handleEditorOverride()}> Click here </a>
```
