### PR TITLE
Fix crashes in Sequence navigation

### LINKED ISSUE #865: Back button after sequences navigation sometimes crashes
Start reading a sequence, eg [here](https://www.lesswrong.com/rationality/preface). Navigate around a bit using the prev/next links at the top and the back button. Sometimes (not clear what the trigger is), the page will be replaced with

```
Error: RangeError: Maximum call stack size exceeded
```

### PR DESCRIPTION
**Pull request by jimrandomh**
Works around a bug in react-helmet by giving `Helmet` a key that changes with every navigation, so that `Helmet.componentShouldUpdate` (which is crashy) doesn't get called. Fixes #865.

### CODE REVIEW

File: packages/lesswrong/components/common/HeadTags.jsx [hunk 1]
```diff
@@ -19,10 +20,10 @@ class HeadTags extends PureComponent {
     const appTitle = getSetting('forumSettings.tabTitle', 'LessWrong 2.0');
     const title = this.props.title ? `${this.props.title} - ${appTitle}` : appTitle;
     const description = this.props.description || getSetting('tagline') || getSetting('description');
-
+    
     return (
       <div>
-        <Helmet>
+        <Helmet key={this.props.location.href}>
```
Comment (Discordius) [inline packages/lesswrong/components/common/HeadTags.jsx]: I was pretty sure the API here should be `location.pathName` or something like that, at least according to: 

https://reacttraining.com/react-router/core/api/location
